---
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    [skip ci]
  autofix_prs: true
  autoupdate_commit_msg: |
    [pre-commit.ci] pre-commit autoupdate

    [skip ci]
  autoupdate_schedule: weekly
  submodules: false

repos:
  - hooks:
      - args: ["--maxkb=800"]
        id: check-added-large-files
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - args:
          - "--allow-multiple-documents"
        id: check-yaml
      - exclude: |
          (?x)^(
          )$
        id: detect-private-key
      - args:
          - "--allow-missing-credentials"
        id: detect-aws-credentials
      - exclude: |
          (?x)^(
          )$
        id: end-of-file-fixer
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - args:
          - "--autofix"
        id: pretty-format-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - args:
          - "--fix"
          - "--select=I"
        id: ruff
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
  - hooks:
      - id: actionlint
    repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
  - hooks:
      - id: shellcheck
    repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.26
  - hooks:
      - args: ["--maxkb=800"]
        id: check-added-large-files
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - args:
          - "--allow-multiple-documents"
        id: check-yaml
      - exclude: |
          (?x)^(
          )$
        id: detect-private-key
      - args:
          - "--allow-missing-credentials"
        id: detect-aws-credentials
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - additional_dependencies: ["@commitlint/config-conventional"]
        id: commitlint
        stages: [commit-msg]
    repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.21.0
  - hooks:
      - id: go-fmt
      - id: go-vet
      # - id: go-lint
      - id: go-imports
      - args: [-over=15]
        id: go-cyclo
      - id: validate-toml
      - id: no-go-testing
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
    repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
